config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
 

  resources :articles

  root 'welcome#index'

  get 'misc/dummy_save' => 'misc#dummy_save'
  get 'misc/dummy_add' => 'misc#dummy_add'

  

end

app/models/article.rb
class Article < ActiveRecord::Base

  #attr_accessible :name, :role, :oncall, :locale, :notes
  
  #validates :title, presence: true, length: { minimum: 5 }
  #validates :text, presence: true, length: { minimum: 1 }
  validates :name, presence: true, length: { minimum: 3 }
  validates :role, presence: true, length: { minimum: 3 }
  validates :oncall, inclusion: { in: [true, false] }
  #validates :oncall, inclusion: { in: [nil] }
  validates :locale, inclusion: { in: %w(nv md china) }
  #validates :locale, presence: true, length: { minimum: 2 }
  validates :notes, presence: true, length: { minimum: 2 }
  
  def self.to_csv(options = {})
    CSV.generate(options) do|csv|
      #csv << column_names
      csv << ['Name', 'Role', 'Oncall', 'Locale', 'Notes']
      all.each do |article|
	#csv << article.attributes.values_at(*column_names)
	csv << [article.name, article.role, article.oncall, article.locale, article.notes]
      end
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
  def index
    @articles = Article.all
    
    respond_to do |format|
      format.html
      #format.csv { render text: @articles.to_csv }
      format.csv { send_data @articles.to_csv, :filename => 'users.csv' }
      #format.csv { send_data @articles.to_csv }
      #format.xls { send_data @articles.to_csv(col_sep: ",") }
      #format.xls { send_data @articles.to_csv(col_sep: "\t") }
      format.xls { send_data @articles.to_csv(col_sep: "\t"), :filename => 'users.xls' }
      
      #format.pdf do ||
	  #pdf = PDF::Writer.new
	  #pdf.text = "test pdf"
	  #send_data pdf.render, :filename => 'users.pdf', :type => 'application/pdf', :disposition => 			'inline'
      #end
    end
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    #@article = Article.new(article_params)
    #if @article.save
    #  redirect_to @article, notice: "Successfully created user."
    #else
    #  render 'new'
    #end
    
    @article = Article.new(article_params)
    @article.save
    
    respond_to do |format|
      #format.html { redirect_to root_url }
      format.html { redirect_to @article, notice: "Successfully created user." }
      format.js
    end
  end

  def update
    @article = Article.find(params[:id])
 
    #original code
    #if @article.update(article_params)
    #  redirect_to @article
    #else
    #  render 'edit'
    #end
    
    #from tutorial
    #@article.update(article_params)
    #respond_with @article
    #requires respond_to at top of controller
    #respond_to :html, :json
    
    respond_to do |format|
     if @article.update(article_params)
        format.html
	format.xml { render :xml => @article }
	format.json { render :json => @article }
#      else
#        format.html { render :action => "edit" }
#        format.json { render :json => @articles.errors.full_messages, :status => #:unprocessable_entity }
      end
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
     redirect_to articles_path, notice: "Successfully destroyed user."
  end

  private
    def article_params
      params.require(:article).permit(:name, :role, :oncall, :locale, :notes)
    end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController

  def dummy_method
  end

  def dummy_save
    redirect_to articles_path, notice: "Saved changes"
  end

  def dummy_add
    redirect_to articles_path, notice: "Added"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/misc_helper.rb
module MiscHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <% if false %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <% end %>
 
  <% if false %>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 <% end %>
 
  <p>
    <%= f.label 'username' %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </p>
 
  <p>
    <%= f.label 'oncall - true or false' %><br>
    <% if false %>
      <%= f.text_field :oncall %>
    <% end %>
    <%= f.select :oncall, [['True', 1],['False', 0]] %>
  </p>
 
  <p>
    <%= f.label 'locale - nv, md, china' %><br>
    <% if false %>
      <%= f.text_field :locale %>
    <% end %>
    <%= f.select :locale, [['NV', 'nv'],['MD', 'md'],['China', 'china']] %>
  </p>
 
  <p>
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>edit - article</h1>

<%= render 'form' %>


<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>index - articles</h1>

<%= link_to 'Home - welcome', {controller: 'welcome', action: 'index'} %>
<br></br>

<%= link_to 'Add new user', new_article_path %>
<br></br>

<% if false %>
<%= link_to 'Add new user-2', { controller: 'articles', action: 'new' } %>
<br></br>
<% end %>

<p>
  Download:
  <%= link_to "CSV", articles_path(format: "csv") %> |
  <%= link_to "XLS", articles_path(format: "xls") %>
</p>

<br></br>

<% if false %>
  <%= link_to "Save", { :controller => 'misc', :action => 'dummy_save' } %>
<% end %>

<% if true %>
  <%= button_to "Save", { controller: 'misc', action: 'dummy_save' }, :method => :get %>
<% end %>

<br></br>

<table id="tableUsers" class="table1">
  <thead>
    <tr>
      <% if false %>
	<th>Title</th>
	<th>Text</th>
      <% end %>
      
      <th>Name</th>
      <th>Role</th>
      <th>onCall</th>
      <th>Locale</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @articles.each do |f| %>
      
      <% if true %>
        <tr>
      <% else %>
	<tr class="<%= cycle('oddrow', 'evenrow') -%>">
      <% end %>
        
        <% if false %>
          <td><%= f.title %></td>
          <td><%= f.text %></td>
        <% end %>
        
        <% if false %>
          <td><%= best_in_place f, :title %></td>
          <td><%= best_in_place f, :text %></td>
        <% end %>
        
        <% if true %>
          <td><%= best_in_place f, :name %></td>
          <td><%= best_in_place f, :role %></td>
          <td><%= best_in_place f, :oncall, type: :checkbox, collection: %w[No Yes] %></td>
	  <td><%= best_in_place f, :locale, type: :select, collection: [["nv", "NV"],
	  ["md", "MD"], ["china", "China"]] %></td>
          <td><%= best_in_place f, :notes, type: :textarea %></td>
	<% end %>
          
        <td><%= link_to 'Show', article_path(f) %></td>
        <td><%= link_to 'Edit', edit_article_path(f) %></td>
        <td><%= link_to 'Destroy', article_path(f),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if true %>
  <%= button_to "Add", { controller: 'misc', action: 'dummy_add' }, :method => :get %>
<% end %>

<% if false %>
  <%= link_to "Add", { controller: 'misc', action: 'dummy_add' } %>
<% end %>


<% if false %>
<p>
  <%= "Task Field" %>
  <%= text_field(:field, :task, size: 20) %>
</p>
<% end %>

<% if false %>
  <%= link_to "Add Task", { controller: 'misc', action: 'dummy_add' } %>
<% end %>



    

app/views/articles/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Role</Data></Cell>
        <Cell><Data ss:Type="String">Oncall</Data></Cell>
        <Cell><Data ss:Type="String">Locale</Data></Cell>
	<Cell><Data ss:Type="String">Notes</Data></Cell>
    </Row>
    <% @articles.each do |article| %>
      <Row>
        <Cell><Data ss:Type="String"><%= article.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.role %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.oncall %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.locale %></Data></Cell>
        <Cell><Data ss:Type="String"><%= article.notes %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/articles/new.html.erb
<h1>new - article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>show - article</h1>
<br></br>

<% if false %>
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>
 
  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @article.role %>
</p>

<p>
  <strong>Oncall:</strong>
  <%= @article.oncall %>
</p>

<p>
  <strong>Locale:</strong>
  <%= @article.locale %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @article.notes %>
</p>

<br></br>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>crud1</h1>
<h1>welcome - index</h1>
<p>app/views/welcome/index.html.erb</p>
<br></br>
<%= link_to 'Users Index', controller: 'articles' %>